task flow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,5 @@
 name: "Vprofile IAC"
+
 on:
   push:
     branches:
@@ -27,20 +28,20 @@ jobs:
       run:
         shell: bash
         working-directory: ./terraform
+
     steps:
-      - name: checkout source code
+      - name: Checkout source code
         uses: actions/checkout@v3
 
-      - name: SetUp Terraform with specified version of the runner
+      - name: Set up Terraform with specified version
         uses: hashicorp/setup-terraform@v2
-
         with:
           terraform_version: 1.6.3
 
       - name: Terraform init
         id: init
         run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
-      
+
       - name: Terraform format
         id: fmt
         run: terraform fmt -check
@@ -48,12 +49,16 @@ jobs:
       - name: Terraform validate
         id: validate
         run: terraform validate
-      
+
       - name: Terraform plan
         id: plan
-        run: terraform plan -no-color -input=false -out=planfile
+        run: |
+          terraform plan -no-color -input=false -out=planfile
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
         continue-on-error: true
-      
+
       - name: Terraform plan status
-        if: steps.plan.outputs== 'failure'
-        run: exit 1
+        if: steps.plan.outputs.exit_code != '0'
+        run: |
+          echo "Terraform plan failed"
+          exit 1
